-- DML TABLE PERSON

INSERT INTO PERSON (NAME, ENTRY_DATE) VALUES ('Emma' ,'2020-12-01');
INSERT INTO PERSON (NAME, ENTRY_DATE) VALUES ('Noah', '2020-06-01');
INSERT INTO PERSON (NAME, ENTRY_DATE) VALUES ('Olivia', '2019-12-01');
INSERT INTO PERSON (NAME, ENTRY_DATE) VALUES ('Liam', '2019-06-01');
INSERT INTO PERSON (NAME, ENTRY_DATE) VALUES ('Ava', '2018-12-01');
INSERT INTO PERSON (NAME, ENTRY_DATE) VALUES ('William', '2018-06-01');
INSERT INTO PERSON (NAME, ENTRY_DATE) VALUES ('Sophia', '2017-12-01');
INSERT INTO PERSON (NAME, ENTRY_DATE) VALUES ('Mason', '2017-06-01');
INSERT INTO PERSON (NAME, ENTRY_DATE) VALUES ('Isabella', '2016-12-01');
INSERT INTO PERSON (NAME, ENTRY_DATE) VALUES ('James', '2016-06-01');
INSERT INTO PERSON (NAME, ENTRY_DATE) VALUES ('Mia', '2015-12-01');
INSERT INTO PERSON (NAME, ENTRY_DATE) VALUES ('Benjamin', '2015-06-01');
INSERT INTO PERSON (NAME, ENTRY_DATE) VALUES ('Charlotte', '2014-12-01');
INSERT INTO PERSON (NAME, ENTRY_DATE) VALUES ('Jacob', '2014-06-01');
INSERT INTO PERSON (NAME, ENTRY_DATE) VALUES ('Abigail', '2013-12-01');
INSERT INTO PERSON (NAME, ENTRY_DATE) VALUES ('Michael', '2013-06-01');
INSERT INTO PERSON (NAME, ENTRY_DATE) VALUES ('Emily', '2012-12-01');
INSERT INTO PERSON (NAME, ENTRY_DATE) VALUES ('Elijah', '2012-06-01');
INSERT INTO PERSON (NAME, ENTRY_DATE) VALUES ('Harper', '2011-12-01');
INSERT INTO PERSON (NAME, ENTRY_DATE) VALUES ('Ethan', '2011-06-01');
INSERT INTO PERSON (NAME, ENTRY_DATE) VALUES ('Amelia', '2010-12-01');
INSERT INTO PERSON (NAME, ENTRY_DATE) VALUES ('Alexander', '2010-06-01');
INSERT INTO PERSON (NAME, ENTRY_DATE) VALUES ('Evelyn', '2009-12-01');
INSERT INTO PERSON (NAME, ENTRY_DATE) VALUES ('Oliver', '2009-06-01');
INSERT INTO PERSON (NAME, ENTRY_DATE) VALUES ('Elizabeth', '2008-12-01');
INSERT INTO PERSON (NAME, ENTRY_DATE) VALUES ('Daniel', '2008-06-01');
INSERT INTO PERSON (NAME, ENTRY_DATE) VALUES ('Sofia', '2007-12-01');
INSERT INTO PERSON (NAME, ENTRY_DATE) VALUES ('Lucas', '2007-06-01');
INSERT INTO PERSON (NAME, ENTRY_DATE) VALUES ('Madison', '2006-12-01');
INSERT INTO PERSON (NAME, ENTRY_DATE) VALUES ('Matthew', '2006-06-01');
INSERT INTO PERSON (NAME, ENTRY_DATE) VALUES ('Avery', '2005-12-01');


-- DML TABLE RESPONSE

-- EMMA RESPONSES
INSERT INTO RESPONSE (XID_QUESTION, XID_PERSON, RESPONSE)
VALUES ((SELECT ID FROM QUESTION WHERE QUESTION='What’s your name?'),
        (SELECT ID FROM PERSON WHERE NAME='Emma'),
        'Emma');

INSERT INTO RESPONSE (XID_QUESTION, XID_PERSON, RESPONSE)
VALUES ((SELECT ID FROM QUESTION WHERE QUESTION='Where are you from?'),
        (SELECT ID FROM PERSON WHERE NAME='Emma'),
        'London');

INSERT INTO RESPONSE (XID_QUESTION, XID_PERSON, RESPONSE)
VALUES ((SELECT ID FROM QUESTION WHERE QUESTION='What’s your current job position?'),
        (SELECT ID FROM PERSON WHERE NAME='Emma'),
        'QA Engineer');
-- NOAH RESPONSES

INSERT INTO RESPONSE (XID_QUESTION, XID_PERSON, RESPONSE)
VALUES ((SELECT ID FROM QUESTION WHERE QUESTION='How old are you?'),
        (SELECT ID FROM PERSON WHERE NAME='Noah'),
        '32');

INSERT INTO RESPONSE (XID_QUESTION, XID_PERSON, RESPONSE)
VALUES ((SELECT ID FROM QUESTION WHERE QUESTION='Where are you from?'),
        (SELECT ID FROM PERSON WHERE NAME='Noah'),
        'Brighton');

INSERT INTO RESPONSE (XID_QUESTION, XID_PERSON, RESPONSE)
VALUES ((SELECT ID FROM QUESTION WHERE QUESTION='What’s your current job position?'),
        (SELECT ID FROM PERSON WHERE NAME='Noah'),
        'Project Manager');
-- OLIVIA RESPONSES
INSERT INTO RESPONSE (XID_QUESTION, XID_PERSON, RESPONSE)
VALUES ((SELECT ID FROM QUESTION WHERE QUESTION='What’s your name?'),
        (SELECT ID FROM PERSON WHERE NAME='Olivia'),
        'Olivia');

INSERT INTO RESPONSE (XID_QUESTION, XID_PERSON, RESPONSE)
VALUES ((SELECT ID FROM QUESTION WHERE QUESTION='How old are you?'),
        (SELECT ID FROM PERSON WHERE NAME='Olivia'),
        '33');

INSERT INTO RESPONSE (XID_QUESTION, XID_PERSON, RESPONSE)
VALUES ((SELECT ID FROM QUESTION WHERE QUESTION='What’s your current job position?'),
        (SELECT ID FROM PERSON WHERE NAME='Olivia'),
        'Senior Developer');
-- LIAM RESPONSES
INSERT INTO RESPONSE (XID_QUESTION, XID_PERSON, RESPONSE)
VALUES ((SELECT ID FROM QUESTION WHERE QUESTION='What’s your name?'),
        (SELECT ID FROM PERSON WHERE NAME='Liam'),
        'Liam');

INSERT INTO RESPONSE (XID_QUESTION, XID_PERSON, RESPONSE, COMMENTS)
VALUES ((SELECT ID FROM QUESTION WHERE QUESTION='Where are you from?'),
        (SELECT ID FROM PERSON WHERE NAME='Liam'),
        'Zafra', 'I do not know anybody called Liam in Zafra...');

INSERT INTO RESPONSE (XID_QUESTION, XID_PERSON, RESPONSE, COMMENTS)
VALUES ((SELECT ID FROM QUESTION WHERE QUESTION='What’s your current job position?'),
        (SELECT ID FROM PERSON WHERE NAME='Liam'),
        'Master of Universe', 'That is not a role...');

-- MASON RESPONSES

INSERT INTO RESPONSE (XID_QUESTION, XID_PERSON, RESPONSE)
VALUES ((SELECT ID FROM QUESTION WHERE QUESTION='What’s your name?'),
        (SELECT ID FROM PERSON WHERE NAME='Mason'),
        'Mason');

INSERT INTO RESPONSE (XID_QUESTION, XID_PERSON, RESPONSE)
VALUES ((SELECT ID FROM QUESTION WHERE QUESTION='How old are you?'),
        (SELECT ID FROM PERSON WHERE NAME='Mason'),
        '90');

INSERT INTO RESPONSE (XID_QUESTION, XID_PERSON, RESPONSE, COMMENTS)
VALUES ((SELECT ID FROM QUESTION WHERE QUESTION='Where are you from?'),
        (SELECT ID FROM PERSON WHERE NAME='Mason'),
        'Vladivostok', 'Quite far, I know..');

INSERT INTO RESPONSE (XID_QUESTION, XID_PERSON, RESPONSE, COMMENTS)
VALUES ((SELECT ID FROM QUESTION WHERE QUESTION='What’s your current job position?'),
        (SELECT ID FROM PERSON WHERE NAME='Mason'),
        'Janitor', 'Best janitor ever');